services:
  django:
    container_name: orderbot_backend
    build:
      context: .
      dockerfile: Dockerfile.django
    networks:
      - orderbot-network
    # ports:
    #   - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate &&
      uvicorn orderbot.asgi:application --host 0.0.0.0 --port 8000"

  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WEBHOOK_PORT=9000
    networks:
      - orderbot-network

  react:
    container_name: orderbot_frontend
    build:
      context: .
      dockerfile: Dockerfile.react
    networks:
      - orderbot-network
    depends_on:
      - django
      - webhook
    ports:
      - "8080:8080"

networks:
  orderbot-network:
    driver: bridge