FROM python:3.10.5-slim-bullseye

WORKDIR /app
ENV PYTHONPATH "${PYTHONPATH}:/app" 

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    sqlite3 \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false

RUN poetry install --no-dev

COPY orderbot /app

ENV DJANGO_SETTINGS_MODULE=orderbot.settings.production

EXPOSE 8000
