services:
  django:
    container_name: orderbot_backend
    build:
      context: .
      dockerfile: Dockerfile.django
    networks:
      - orderbot-network
    command: >
      sh -c "
      python manage.py migrate &&
      uvicorn orderbot.asgi:application --host 0.0.0.0 --port 8000"

  react:
    container_name: orderbot_frontend
    build:
      context: .
      dockerfile: Dockerfile.react
    networks:
      - orderbot-network
    depends_on:
      - django
    ports:
      - "8080:8080"

networks:
  orderbot-network:
    driver: bridge