# Generated by Django 4.1.13 on 2024-05-11 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_orderstatuschange_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatusChange',
            new_name='OrderStatus',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.orderstatus'),
        ),
    ]
