# Generated by Django 4.1.13 on 2024-05-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_orderstatuschange_orderstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatus",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="products.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("order", "주문 완료"),
                    ("payment_completed", "입금 완료"),
                    ("order_changed", "주문 변경"),
                    ("order_canceled", "주문 취소"),
                ],
                default="order",
                max_length=50,
            ),
        ),
    ]
