# Generated by Django 4.1.13 on 2024-05-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_orderstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order', '주문 완료'), ('payment_completed', '입금 완료'), ('order_changed', '주문 변경'), ('order_canceled', '주문 취소')], default='order', max_length=50, null=True),
        ),
    ]
